server {
    listen ${PORT};
    server_name _;

    client_max_body_size 20M;

    root /var/www/frontend/dist;
    index index.html;

    location = /up {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/api/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/api/public;
        fastcgi_param REQUEST_URI /up;
    }

    location /api {
        rewrite ^/api/?(.*)$ /$1 break;

        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/api/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/api/public;
        fastcgi_param REQUEST_URI $uri$is_args$args;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
